### ISSUE TITLE
Config functionality checklist

### ISSUE THREAD

**Issue by squeek502** [progwml6/HungerOverhaul#11]
Used some regex replacement to generate this using the HO config file. Items should only be checked off once they have been confirmed to be working.

**Bolded items** are new config options added in the 1.7.10 version.
### Custom field
- [x] addCustomVillageField (Adds a custom field to villages)
- [x] fieldNormalWeight (Weighted chance for custom field to contain 'normal' crops)
- [x] fieldReedWeight (Weighted chance for custom field to contain reeds)
- [x] fieldStemWeight (Weighted chance for custom field to contain pumpkins/melons)
### Delays
- [x] breedingTimeoutMultiplier (Multiplier applied to the delay between breeding entities)
- [x] cactusRegrowthMultiplier (Multiplier on the time it takes cactus to grow)
- [x] childDurationMultiplier (Multiplier applied to the delay before children become adults)
- [x] cocoaRegrowthMultiplier (Multiplier on the time it takes cocoa to grow)
- [x] cropRegrowthMultiplier (Multiplier on the time it takes a non-tree crop to grow)
- [x] dryingRackTimeMultiplier (Multiplier on the time it takes food to dry on Tinkers' Construct drying racks)
- [x] eggTimeoutMultiplier (Multiplier applied to the delay between chicken egg laying)
- [x] flowerRegrowthMultiplier (Multiplier on the time it takes a WeeeFlower crop to grow)
- [x] milkedTimeout (Delay (in minutes) after milking a cow before it can be milked again)
- [x] **netherWartRegrowthMultiplier (Multiplier on the time it takes nether wart to grow)**
- [x] noSunlightRegrowthMultiplier (Multipier on crop growth time without sunlight (1 to disable feature, 0 to make crops only grow in sunlight))
- [x] saplingRegrowthMultiplier (Multiplier on the time it takes a sapling to grow into a tree)
- [x] sugarcaneRegrowthMultiplier (Multiplier on the time it takes sugarcane to grow)
- [x] treeCropRegrowthMultiplier (Multiplier on the time it takes a tree crop to grow)
- [x] wrongBiomeRegrowthMultiplier (Multipier on crop growth time (except sugarcane) in the wrong biome (1 to disable feature, 0 to make crops only grow in correct biome))
- [x] wrongBiomeRegrowthMultiplierSugarcane (Multipier on sugarcane growth time in the wrong biome (1 to disable feature, 0 to make sugarcane only grow in correct biome))
### Difficulty scaling
- [x] difficultyScaling (Enable/Disable all difficulty scaling effect in one setting)
- [x] difficultyScalingBoneMeal (Effects of bone meal dependant of difficulty ('difficultyScaling' must be true))
- [x] difficultyScalingEffects (Negative effects on low health/hunger scale by difficulty ('difficultyScaling' must be true))
- [x] difficultyScalingHealing (Healing rate scales by difficulty ('difficultyScaling' must be true))
- [x] difficultyScalingHunger (Hunger loss rate scales by difficulty ('difficultyScaling' must be true))
- [x] difficultyScalingRespawnHunger (Hunger value after respawn is affected by difficulty ('difficultyScaling' must be true))
- [x] ~~difficultyScalingSleepHungerLoss (Hunger loss while sleeping depends on difficulty ('addSleepHungerLoss' and 'difficultyScaling' must be true))~~ (removed, see 94a7353)
### Food
- [x] addFoodTooltips (Add tooltips to food items showing hints at food value)
- [x] addWellFedEffect (Adds a 'well fed' effect that gives slight health regen)
- [x] foodStackSizeMultiplier (Multiplier on the stack size of food ('modifyFoodStackSize' must be true))
- [x] modFoodValueDivider (Other mod's food replenishment values are divided by this ('modifyFoodValues' must be true))
- [x] modifyFoodEatingSpeed (Changes the eating animation speed to be dependant on the food's replenishment value)
- [x] modifyFoodStackSize (Changes the stack size of food to be dependant on the food's replenishment value)
- [x] modifyFoodValues (Changes the replenishment value of vanilla and HarvestCraft foods)
### Getting seeds
- [x] allSeedsEqual (Each seed has an equal chance to drop (grass drops and via hoes))
- [x] hoeToolDamageMultiplier (Multiplier on tool damage taken when a hoe is used)
- [x] modifyHoeUse (Changes the use of hoes depending on the availability of water)
- [x] removeHoeRecipes (Whether wood and stone hoe recipes are removed)
- [x] removeTallGrassSeeds (Removes seed drops when breaking tall grass)
- [x] seedChance (Chance for seed to drop from hoe use on normal difficulty)
### Harvestcraft
- [x] addHarvestCraftChestLoot (HarvestCraft items added to dungeon/temple chests (Harvestcraft))
- [x] addTradesButcher (Add high tier HarvestCraft foods to the items butcher villagers will sell (HarvestCraft))
- [x] **addCropTradesFarmer (Add HarvestCraft crop produce to the items farmer villagers will buy (HarvestCraft))** (renamed from addTradesFarmer; was not functional in 1.6.4)
- [x] **addSaplingTradesFarmer (Add HarvestCraft saplings to the items farmer villagers will sell (HarvestCraft))**
- [x] chestLootChance (Weighted chance for food to be found in chests (addHarvestCraftChestLoot must be true))
- [x] **foodsUnplantable (Makes HarvestCraft foods unplantable, meaning seeds are required to plant crops)**
### Harvesting
- [x] producePerHarvestMax (Maximum number of produce you get when harvesting a non-tree crop)
- [x] producePerHarvestMin (Minimum number of produce you get when harvesting a non-tree crop)
- [x] seedsPerHarvestMax (Maximum number of seeds you get when harvesting a non-tree crop)
- [x] seedsPerHarvestMin (Minimum number of seeds you get when harvesting a non-tree crop)
### Health
- [x] foodHealDivider (Amount of health food restores is the food value divided by this number (foodRegensHealth must be true))
- [x] foodRegensHealth (Eating food regenerates health)
- [x] healthRegenRatePercentage (Speed up or slow down the rate that health regenerates (0 to disable regen))
- [x] lowHealthRegenRateModifier (The lower your health the longer it takes to regen, modify the effect here (lower = less effect))
- [x] minHungerToHeal (Minimum hunger level before healing starts (vanilla default is 18))
### Hunger
- [x] addSetHungerCommand (Adds a console command to allow OPs to set a player's hunger level)
- [x] ~~addSleepHungerLoss (Enable/disable hunger loss while sleeping)~~ (removed, see 94a7353)
- [x] constantHungerLoss (You lose hunger (very slowly) at all times)
- [x] damageOnStarve (Amount of damage you take when hunger hits zero (vanilla default 2))
- [x] disableHealingHungerDrain (Disable the hunger drain when healing that was introduced in vanilla 1.6.2)
- [x] hungerLossRatePercentage (Speed up or slow down the rate that hunger drops (set to 0 to disable hunger loss))
- [x] respawnHungerDifficultyModifier (The amount difficulty modifies the hunger value set after respawning  ('difficultyScaling' and 'difficultyScalingRespawnHunger' must be true))
- [x] respawnHungerValue (hunger value set after respawning for peaceful/easy difficulty (vanilla default is 20))
### Low stats
- [x] addGuiText (Shows onscreen text when hunger/health is low)
- [x] addLowStatEffects (Enables/disables all low hunger/health effects)
- [x] addLowStatMiningSlowdown (Mining slowdown effect when health/hunger is low ('addLowStatEffects' must be true))
- [x] addLowStatNausea (Nausea effect when hunger is really low ('addLowStatEffects' must be true))
- [x] addLowStatSlowness (Slowness effect when health/hunger is low ('addLowStatEffects' must be true))
- [x] addLowStatWeakness (Weakness effect when health/hunger is low ('addLowStatEffects' must be true))
### Potion ids
- [x] ~~wellFedID (Potion ID for the 'Well Fed' effect (maximum 31))~~ (removed)
### ~~Rotting~~
- [x] ~~addFoodRotting (Turning on causes food to spoil over time (currently buggy))~~ (removed)
- [x] ~~foodRotSpeed (Rate at which food rots (in ticks))~~ (removed)
