### ISSUE TITLE
Reimplementation task list

### ISSUE THREAD

**Issue by squeek502** [progwml6/HungerOverhaul#5]
Incomplete list of things that need to be done. Will be added to/edited as things move forward.
#### From IguanaFoodStats
- [x] Player field
- [x] Food value modification support
- [ ] Food value modifications
  - [ ] Vanilla
  - [ ] HarvestCraft
  - [ ] TConstruct
  - [ ] Natura
  - [ ] Catch-all food value division for anything not specifically modified (IguanaConfig.modFoodValueDivider)
- [x] Food regens health (config option)
- [ ] Configurable damage on starve
- [ ] Configurable max foodExhaustionLevel
- [ ] IguanaConfig.hungerLossRatePercentage being zero stopping food stats from changing/keeping it at a specific level (19/0/0)
- [ ] Configurable minimum hunger to theal (IguanaConfig.minHungerToHeal)
- [ ] Configurable time between health regen from hunger (multiple config options)
- [ ] Separate starve timer from food timer
#### From IguanaFood
- [ ] Well fed buff (should be added to FoodEventHandler.onFoodEaten)
- [ ] Stacksize modifications
- [ ] Village trading/chest loot additions
- [ ] Food eating speed modification
- [ ] Food value tooltips (should use Forge's ItemTooltipEvent)
